import { Pool } from "pg";
import { config } from "./config.mjs";

let pool;

const schemaStatements = [
    `
    CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(64) NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL,
        display_name VARCHAR(128) NOT NULL,
        avatar_url TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    `,
    `
    CREATE TABLE IF NOT EXISTS books (
        id TEXT NOT NULL PRIMARY KEY,
        name VARCHAR(128) NOT NULL,
        owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        meta_json JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    `,
    `
    CREATE TABLE IF NOT EXISTS book_members (
        book_id TEXT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
        user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        role TEXT NOT NULL DEFAULT 'editor' CHECK (role IN ('owner', 'editor')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (book_id, user_id),
        UNIQUE (book_id, user_id)
    );
    `,
    `
    CREATE TABLE IF NOT EXISTS book_entries (
        id TEXT NOT NULL PRIMARY KEY,
        book_id TEXT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
        creator_id BIGINT NOT NULL,
        type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
        category_id VARCHAR(128) NOT NULL,
        comment TEXT NULL,
        amount BIGINT NOT NULL,
        occurred_at BIGINT NOT NULL,
        images_json JSONB NULL,
        location_json JSONB NULL,
        tag_ids_json JSONB NULL,
        currency_json JSONB NULL,
        extra_json JSONB NULL,
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL
    );
    `,
    `
    CREATE TABLE IF NOT EXISTS assets (
        id TEXT NOT NULL PRIMARY KEY,
        book_id TEXT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
        uploader_id BIGINT NOT NULL,
        file_name VARCHAR(255) NOT NULL,
        mime_type VARCHAR(128) NOT NULL,
        blob_data BYTEA NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    `,
    `
    CREATE INDEX IF NOT EXISTS idx_books_owner_id ON books (owner_id);
    `,
    `
    CREATE INDEX IF NOT EXISTS idx_book_entries_book_time
    ON book_entries (book_id, occurred_at DESC);
    `,
    `
    CREATE INDEX IF NOT EXISTS idx_book_entries_book_creator
    ON book_entries (book_id, creator_id);
    `,
    `
    CREATE INDEX IF NOT EXISTS idx_assets_book_id ON assets (book_id);
    `,
];

const normalizeSql = (statement) => {
    let index = 0;
    return statement.replace(/\?/g, () => `$${++index}`);
};

const wrapClient = (client) => ({
    query: async (statement, params = []) => {
        return await client.query(normalizeSql(statement), params);
    },
});

const getPool = () => {
    if (!pool) {
        pool = new Pool({
            host: config.db.host,
            port: config.db.port,
            user: config.db.user,
            password: config.db.password,
            database: config.db.database,
            max: config.db.connectionLimit,
            idleTimeoutMillis: 10000,
            connectionTimeoutMillis: 10000,
        });
    }
    return pool;
};

export const query = async (statement, params = []) => {
    return await getPool().query(normalizeSql(statement), params);
};

export const ensureSchema = async () => {
    for (const statement of schemaStatements) {
        await getPool().query(statement);
    }
};

export const withTransaction = async (callback) => {
    const connection = await getPool().connect();
    const transaction = wrapClient(connection);
    try {
        await connection.query("BEGIN");
        const result = await callback(transaction);
        await connection.query("COMMIT");
        return result;
    } catch (error) {
        try {
            await connection.query("ROLLBACK");
        } catch {
            // Ignore rollback errors caused by a broken connection.
        }
        throw error;
    } finally {
        connection.release();
    }
};
